### ISSUE TITLE
OpenPose Editor is not working properly.

### ISSUE THREAD

**Issue by iJustGhost** [fkunn1326/openpose-editor#99]
**Describe the bug**
OpenPose Editor tab is not properly working.

**To Reproduce**
1. Click send to txt2img.
2. Check controlnet in txt2img tab.
3. Pose is not applied.

**Expected behavior**
Pose should be applied.

**Additional context**
Probably happened after automatic1111's web ui repo update.

**Comment by vienduong88** [comment]
I have the same problem.

**Comment by FireworkTM** [comment]
The HTML layout of webui is changed.

There is a temporarily sulotion, edit this file: webui\extensions\openpose-editor\javascript\main.js
(Remember to backup the file before editing)

Find following code, ~line 482
-----------------------
const accordion = gradioApp().querySelector(selector).querySelector("#controlnet .transition");
        if (accordion.classList.contains("rotate-90")) {
            accordion.click()
        }
        		
        const tabs = gradioApp().querySelector(selector).querySelectorAll("#controlnet > div:nth-child(2) > .tabs > .tabitem, #controlnet > div:nth-child(2) > div:not(.tabs)")
        const tab = tabs[index]
        if (tab.classList.contains("tabitem")) {
            tab.parentElement.firstElementChild.querySelector(`:nth-child(${Number(index) + 1})`).click()
        }
        const input = tab.querySelector("input[type='file']")
        try {
            input.previousElementSibling.previousElementSibling.querySelector("button[aria-label='Clear']").click()
        } catch (e) {
            console.error(e)
        }
-----------------
replace with:
------------------
		// 20230328 JY 
        const accordion = gradioApp().querySelector(selector).querySelector("#controlnet").querySelectorAll("span.icon.svelte-s1r2yt")[0];
				
		// Show controlNet box
		let rotate = accordion.style.transform.match(/rotate\((\d+)(.+)\)/);
		if (rotate) {
			let [num, unit] = rotate.slice(1);  
			if (num == "90") {
				accordion.click()
			}
		}	
		const input = gradioApp().querySelector(selector).querySelector("#controlnet").querySelector("input[type='file']");
---------------------
reload webui.

**Comment by fkunn1326** [comment]
@FireworkTM Could you please send me a pull request?

**Comment by iJustGhost** [comment]
> The HTML layout of webui is changed.
> 
> There is a temporarily sulotion, edit this file: webui\extensions\openpose-editor\javascript\main.js (Remember to backup the file before editing)
> 
> ## Find following code, ~line 482
> const accordion = gradioApp().querySelector(selector).querySelector("#controlnet .transition"); if (accordion.classList.contains("rotate-90")) { accordion.click() }
> 
> ```
>     const tabs = gradioApp().querySelector(selector).querySelectorAll("#controlnet > div:nth-child(2) > .tabs > .tabitem, #controlnet > div:nth-child(2) > div:not(.tabs)")
>     const tab = tabs[index]
>     if (tab.classList.contains("tabitem")) {
>         tab.parentElement.firstElementChild.querySelector(`:nth-child(${Number(index) + 1})`).click()
>     }
>     const input = tab.querySelector("input[type='file']")
>     try {
>         input.previousElementSibling.previousElementSibling.querySelector("button[aria-label='Clear']").click()
>     } catch (e) {
>         console.error(e)
>     }
> ```
> 
> ## replace with:
> ```
> 	// 20230328 JY 
>     const accordion = gradioApp().querySelector(selector).querySelector("#controlnet").querySelectorAll("span.icon.svelte-s1r2yt")[0];
> 			
> 	// Show controlNet box
> 	let rotate = accordion.style.transform.match(/rotate\((\d+)(.+)\)/);
> 	if (rotate) {
> 		let [num, unit] = rotate.slice(1);  
> 		if (num == "90") {
> 			accordion.click()
> 		}
> 	}	
> 	const input = gradioApp().querySelector(selector).querySelector("#controlnet").querySelector("input[type='file']");
> ```
> 
> reload webui.

Tried this one, but dragging while everything is selected is not working.
Still it works.

**Comment by Liz2rdWizard** [comment]
The problem is still not fixed, basically the plugin is currently unusable and I'm using blender for posing for now. I tried the temporary fix by FireworkTM, it did not work for me.

There is no such button as "send to controlnet" as I see in every youtube video, but also the "send to text2img" button is not sending the pose to where it should, but only brings me to the "text2img" tab and does nothing else (as reported by other users already)

**Comment by fkunn1326** [comment]
Fixed in https://github.com/fkunn1326/openpose-editor/commit/8f17b06495ea790e16def374a6eb151e0fb29c6f.
Please close this issue after confirming that it works properly

**Comment by iJustGhost** [comment]
Still didn't fixed, maybe theres another problem.

**Comment by fkunn1326** [comment]
If updating the webui and this extension doesn't fix it, open your browser's console and show me

**Comment by Tramy00** [comment]
![image](https://user-images.githubusercontent.com/24564769/230590630-9d90ac90-f007-48ca-9c09-7fd8f2a09578.png)

1. I download openpose editor form github(also the openopse model in controlnet)，replace the old one, not work.
2. I download from the webui extention, sitll not work.
3. I try the answer somebody works, still not slove.

The problem come out when i set openpose model on controlnet try to use txt2img.
And webui still working to output a img but  not related to the openpose.

**Comment by Tramy00** [comment]
> ![image](https://user-images.githubusercontent.com/24564769/230590630-9d90ac90-f007-48ca-9c09-7fd8f2a09578.png)
> 
> 1. I download openpose editor form github(also the openopse model in controlnet)，replace the old one, not work.
> 2. I download from the webui extention, sitll not work.
> 3. I try the answer somebody works, still not slove.
> 
> The problem come out when i set openpose model on controlnet try to use txt2img. And webui still working to output a img but not related to the openpose.

I tried to find a way to do it from the comments section of other tutorial bloggers and found one that worked.
 1. find the file below "G:\stable-diffusion-webui\models\openpose":
 2. Delete "hand-pose-model.pth"&"body-pose-model.pth" .
 3. Run de webui-user.bat again, and use openpose model, the file will be download again.
 4. Then you can to use openpose !!

**Comment by jVXgHcey** [comment]
> > ![image](https://user-images.githubusercontent.com/24564769/230590630-9d90ac90-f007-48ca-9c09-7fd8f2a09578.png)
> > 
> > 1. I download openpose editor form github(also the openopse model in controlnet)，replace the old one, not work.
> > 2. I download from the webui extention, sitll not work.
> > 3. I try the answer somebody works, still not slove.
> > 
> > The problem come out when i set openpose model on controlnet try to use txt2img. And webui still working to output a img but not related to the openpose.
> 
> I tried to find a way to do it from the comments section of other tutorial bloggers and found one that worked.
> 
> 1. find the file below "G:\stable-diffusion-webui\models\openpose":
> 2. Delete "hand-pose-model.pth"&"body-pose-model.pth" .
> 3. Run de webui-user.bat again, and use openpose model, the file will be download again.
> 4. Then you can to use openpose !!

thks,Solved
